<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="IN-komehta-W1" failures="1" tests="1" name="ShopforItemsTest" time="0.101" errors="0" timestamp="2019-11-06T20:13:56 IST">
  <testcase classname="boonSupplyTests.ShopforItemsTest" name="GetTrendingItemsforShopping" time="0.033">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality manually.
at boonSupplyTests.ShopforItemsTest.GetTrendingItemsforShopping(ShopforItemsTest.java:95)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- GetTrendingItemsforShopping -->
  <testcase classname="boonSupplyTests.ShopforItemsTest" name="AddA25DollarItemInCart" time="0.0">
    <ignored/>
  </testcase> <!-- AddA25DollarItemInCart -->
  <testcase classname="boonSupplyTests.ShopforItemsTest" name="ValidateCheckoutPageFeatures" time="0.0">
    <ignored/>
  </testcase> <!-- ValidateCheckoutPageFeatures -->
  <testcase classname="boonSupplyTests.ShopforItemsTest" name="AddMultipleItemsInCart" time="0.0">
    <ignored/>
  </testcase> <!-- AddMultipleItemsInCart -->
</testsuite> <!-- ShopforItemsTest -->
